### ISSUE TITLE
Request: Add support for audioStyles

### ISSUE THREAD

**Issue by smilingpeanut** [mostafaznv/larupload#28]
**Problem:**
Upload a video file or lossless audio file like WAV. Need to transcode to a lossy audio format, such as MP3 or AAC.

videoStyles are locked to X264, which makes using any other format impossible with the current structure.

**Solution:**
Add audioStyles that can transcode to audio output using any valid FFMPEG format (MP3/AAC/WAV/OGG, etc.)

**Comment by mostafaznv** [comment]
Hi @smilingpeanut 

First of all, I would like to apologize for the late reply.
Over the past few months, I have been very busy and could only follow up on bug reports and critical updates.

Anyway, I think I will be able to check your feature request in the coming weeks.

I’m considering adding `AudioStyle`, as well as more formats (if possible) to `VideoStyle`.

Just be patient a little more 😄

**Comment by smilingpeanut** [comment]
Hi @mostafaznv. No problem at all! I understand how busy things can be. In the mean time, I've been attempting to add the feature myself as a PR, but this might be above my skillset, so it's nice to hear that you're considering this. Thank you!

**Comment by mostafaznv** [comment]
PRs are always welcome.
However, as the codebase is very complicated (it really needs a refactor 😄), I believe it would be a difficult task to complete.

If you had time to go for it, I can check your PR, otherwise, I will give a shot on it in 10-15 days may be.

**Comment by mostafaznv** [comment]
Update: I have started working on this feature.

Please be patient, as it takes time.
Thank you very much.

**Comment by mostafaznv** [comment]
Hi again, @smilingpeanut,

First of all, thank you for your patience.
As I mentioned before, I’ve been very busy over the last couple of months.

I’ve implemented the feature you requested; however, I’ve held off on publishing it as a final version.
You can download version [2.3.0-rc1](https://github.com/mostafaznv/larupload/releases/tag/2.3.0-rc1) by specifying it in your composer require command or updating your composer.json file.

Please test it, and if everything works as expected, let me know so I can publish the final version.

[Documentation](https://mostafaznv.gitbook.io/larupload/advanced-usage/attachment/media-styles#audio-style)

**Comment by smilingpeanut** [comment]
@mostafaznv Thank you so much! I'll test it right away. Happy holidays to you!

**Comment by smilingpeanut** [comment]
@mostafaznv So far, so good. Mp3, Wav, and Flac all work properly. AAC is failing. The reason for this is that the `libfdk_aac` encoder is not GPL compatible and so is not included with FFMPEG unless a user compiles it themselves. FFMPEG does ship with its own AAC encoder which is compatible so I would suggest to use that (details at https://trac.ffmpeg.org/wiki/Encode/AAC). AAC is also missing in some of the audio tests.

```
[aost#0:0 @ 0x12b608cc0] Unknown encoder 'libfdk_aac'
[aost#0:0 @ 0x12b608cc0] Error selecting an encoder
Error opening output file /[site]/storage/app/public/media/c24da7ec-3182-4ffc-a9df-2b7aff13ca13/media/aac/1e7e8e2dadcb0414a63c525bf359e67d.aac.
Error opening output files: Encoder not found 
```

One request: in the PR, I included support for setting the bitrate for each style, so you could do something like a LQ version at 128kbps and a HQ version at 320kbps for example. Would it be too much trouble to add that?

**Comment by smilingpeanut** [comment]
Another thing I noticed is that if a video is uploaded, the audio styles have no effect. Ideally, audio would be transcoded from the video.

**Comment by mostafaznv** [comment]
> https://trac.ffmpeg.org/wiki/Encode/AAC

Thank you for your detailed testing.
Yes, I’m aware that `AAC` is not included in the official `FFMPEG` builds. However, I’ve added its type to the `AudioStyle` to give users the option to incorporate it into their `FFMPEG` binaries if they choose to do so.
If you have any suggestions in this regard, I’d appreciate hearing them.

Regarding setting the bitrate and other options for each audio format, you can already configure them using the `Wav`, `Mp3`, `Flac`, and `Aac` classes:


```
<?php

namespace App\Models;

use FFMpeg\Format\Audio\Wav;
use FFMpeg\Format\Audio\Flac;
use FFMpeg\Format\Audio\Mp3;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Mostafaznv\Larupload\Storage\Attachment;
use Mostafaznv\Larupload\Traits\Larupload;


class Media extends Model
{
    use Larupload;

    public function attachments(): array
    {
        return [
            Attachment::make('main_file')
                ->audio('audio_wav', new Wav())
                ->audio('audio_flac', new Flac())
                ->audio(
                    name: 'audio_mp3',
                    format: (new Mp3())->setAudioKiloBitrate(192)->setAudioChannels(2)
                )
        ];
    }
}
```

https://mostafaznv.gitbook.io/larupload/advanced-usage/attachment/complete-example

**Comment by mostafaznv** [comment]
> Another thing I noticed is that if a video is uploaded, the audio styles have no effect. Ideally, audio would be transcoded from the video.

Yes, you’re right. For now, `audio` styles only affect `audio` files.
However, this is just the beginning. I plan to add support for converting `video` files to `audio` files in the near future. The functionality has already been implemented, but integrating it into the entire uploading process will take a bit more time. It’s already in the pipeline.

https://github.com/mostafaznv/larupload/blob/dee2b3480c43009ce6c4a50306af22c0942cc274/tests/Unit/FFMpegTest.php#L321-L350

**Comment by smilingpeanut** [comment]
Oh wonderful! I can confirm that setting the parameters that way works. Thank you so much for working on this!

**Comment by smilingpeanut** [comment]
One thing I just noticed in the console. The URLs that are generated for the styles have a `./` inserted. This is not a big deal, but perhaps something to look at at some point.

![Screenshot 2024-12-27 at 5 03 14 PM](https://github.com/user-attachments/assets/e44d5c78-37ac-48cc-a343-c4cfd16cd7d2)

**Comment by mostafaznv** [comment]
The issue with the extra dot has been fixed.
And you can now convert video files to other video and audio formats.

Example:
```php
<?php

namespace App\Models;

use FFMpeg\Format\Audio\Mp3;
use Illuminate\Database\Eloquent\Model;
use Mostafaznv\Larupload\Storage\Attachment;
use Mostafaznv\Larupload\Traits\Larupload;


class Media extends Model
{
    use Larupload;

    public function attachments(): array
    {
        return [
            Attachment::make('video')
                ->video(name: 'mp3', format: new Mp3())
        ];
    }
}
```

**Comment by smilingpeanut** [comment]
Everything is working great so far! Thank you!

**Comment by mostafaznv** [comment]
You’re welcome 🤘🏻
I’ll publish the final version later today.

If anything unexpected arises, feel free to open a new issue.

**Comment by mostafaznv** [comment]
https://github.com/mostafaznv/larupload/releases/tag/2.3.0
