### ISSUE TITLE
Exception on null file_meta column

### ISSUE THREAD

**Issue by afshiinasghari** [mostafaznv/larupload#3]
Hey there, 

I've noticed whenever file_meta column state was null or in general terms no file was uploaded for given model instance,

using:

`$model->meta('column_name', 'duration')`

would cause an exception as following:
```
#message: "First parameter must either be an object or the name of an existing class"
#code: 0
#file: "../src/Storage/Attachment.php"
#line: 430
```

**Comment by mostafaznv** [comment]
bug fixed and released under 0.0.11 version
